export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
export const AUTH_ERROR = 'AUTH ERROR';
export const USER_FETCHED = 'USER_FETCHED';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';

export const POSTS_SUCCESS = 'POSTS_SUCCESS';
export const POSTS_FAIL = 'POSTS_FAIL';
export const POSTS_FETCH_REQUEST = 'POSTS_FETCH_REQUEST';

export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAIL = 'POST_FAIL';
export const POST_FETCH_REQUEST = 'POST_FETCH_REQUEST';

export const POST_ADD_FETCH_REQUEST = 'POST_ADD_FETCH_REQUEST';
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';
export const POST_ADD_FAIL = 'POST_ADD_FAIL';

export const POST_EDIT_FETCH_REQUEST = 'POST_EDIT_FETCH_REQUEST';
export const POST_EDIT_SUCCESS = 'POST_EDIT_SUCCESS';
export const POST_EDIT_FAIL = 'POST_EDIT_FAIL';

export const POST_DELETE_FETCH_REQUEST = 'POST_DELETE_FETCH_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';
